// <auto-generated />
namespace FYP.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class SaltAndStatusString : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SaltAndStatusString));
        
        string IMigrationMetadata.Id
        {
            get { return "202001271914189_SaltAndStatusString"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
